### ISSUE TITLE
[EPIC] DataFusion Ray Testing

### ISSUE THREAD

**Issue by edmondop** [apache/datafusion-ray#18]
Set-up various type of testing for DataFusion:
- [x] [Compare expected and observed plans in CI](https://github.com/apache/datafusion-ray/issues/9)
- [ ] [Compare results produced by DataFusion Ray and DataFusion](https://github.com/apache/datafusion-ray/issues/11)
- [ ] Run tests on K8s

**Comment by edmondop** [comment]
I wonder whether we should only run tpch queries on Kubernetes and skip completely running them on single ray node locally @andygrove
